### ISSUE TITLE
Panic in glog

### ISSUE THREAD

**Issue by tzdybal** [ethereumclassic/go-ethereum#17]
[As seen on CircleCI](https://circleci.com/gh/ethereumclassic/go-ethereum/381I):
```
I0113 20:53:25.840588 glog_test.go:197] test
E0102 15:04:05.067890 logger/glog/glog_test.go:220] test
E0113 20:53:25.840685 logger/glog/glog_test.go:268] test
2019-01-13 20:53:25 test
2019-01-13 20:53:25 [ERR ] test
2019-01-13 20:53:25 test
panic: interface conversion: glog.flushSyncWriter is *glog.flushBuffer, not *glog.syncBuffer

goroutine 43 [running]:
github.com/ethereumclassic/go-ethereum/logger/glog.(*syncBuffer).getCurrentLogs(0xc420058c00, 0x559800, 0xc42000cf40, 0xc42003ee08)
	/home/circleci/go/src/github.com/ethereumclassic/go-ethereum/logger/glog/glog.go:1305 +0x285
github.com/ethereumclassic/go-ethereum/logger/glog.(*syncBuffer).excludeActive(0xc420058c00, 0xc420114bd0, 0x2, 0x2, 0x0, 0x629f28, 0x629f68)
	/home/circleci/go/src/github.com/ethereumclassic/go-ethereum/logger/glog/glog.go:1283 +0x43
github.com/ethereumclassic/go-ethereum/logger/glog.(*syncBuffer).rotateOld(0xc420058c00, 0xbf070731b22ef46b, 0x3bcca470, 0x672460)
	/home/circleci/go/src/github.com/ethereumclassic/go-ethereum/logger/glog/glog.go:1219 +0x191
created by github.com/ethereumclassic/go-ethereum/logger/glog.(*syncBuffer).Write
	/home/circleci/go/src/github.com/ethereumclassic/go-ethereum/logger/glog/glog.go:1108 +0x1aa
FAIL	github.com/ethereumclassic/go-ethereum/logger/glog	1.009s
?   	github.com/ethereumclassic/go-ethereum/metrics	[no test files]
?   	github.com/ethereumclassic/go-ethereum/miner	[no test files]
ok  	github.com/ethereumclassic/go-ethereum/node	1.507s
ok  	github.com/ethereumclassic/go-ethereum/p2p	0.204s
ok  	github.com/ethereumclassic/go-ethereum/p2p/discover	7.016s
ok  	github.com/ethereumclassic/go-ethereum/p2p/distip	0.001s
ok  	github.com/ethereumclassic/go-ethereum/p2p/nat	0.504s
?   	github.com/ethereumclassic/go-ethereum/pow	[no test files]
ok  	github.com/ethereumclassic/go-ethereum/rlp	0.006s
ok  	github.com/ethereumclassic/go-ethereum/rpc	1.004s
ok  	github.com/ethereumclassic/go-ethereum/tests	20.023s
ok  	github.com/ethereumclassic/go-ethereum/trie	4.043s
ok  	github.com/ethereumclassic/go-ethereum/whisper	5.424s
Exited with code 1
```

**Comment by tzdybal** [comment]
`glog.flushBuffer` is used only in tests.

**Comment by lostinblue** [comment]
Glog is kinda trash library anyways, less dependencies is always better when dealing with cryptocurrencies and security.

If you need recommendations I'm very very familiar wtih the current stat of libraries for both Go and Rust. (and C but hahaha we aint doint that shit).
